### ISSUE TITLE
Milestone #1: Absolutely Essential features

### ISSUE THREAD

**Issue by AriaMoradi** [Suwayomi/Suwayomi-Server#2]
## super early state
- [x] prototyping ability to run extensions
- [x] back-end server project
- [x] react UI project

## essential feature set
- [x] extensions page
    - [x] list extensions
        - [x] API
        - [x] UI
        - [x] UI functionality
    - [x] install extensions
        - [x] API
        - [x] UI
        - [x] UI functionality
- [x] source list page
    - [x] API
    - [x] UI
    - [x] UI functionality
- [x] popular/latest mangas page
    - [x] API
    - [x] UI
    - [x] UI functionality
        - [x] infinite scrolling to fetch pages beyond 1
- [x] manga page
    - [x] API
        - [x] manga details
        - [x] chapter list
    - [x] UI
    - [x] UI functionality
- [x] chapter page reader
    - [x] API
    - [x] pages reader
        - [x] UI
        - [x] UI functionality
- [x] manga search
    - [x] API
    - [x] UI
## optional/quality of life feature set
- [ ] extensions page
    - [x] offline fast loading
        - [x] API
        - [x] UI functionality
    - [x] online slow loading
        - [x] API
        - [x] UI functionality        
    - [ ] loading animation
        - [ ] UI
        - [ ] UI functionality
    - [ ] group by language
        - [ ] UI
        - [ ] UI functionality
- [x] chapter reader page
    - [x] vertical all pages reader
        - [x] UI
        - [x] UI functionality
